version: '3'

services:
  electech:
    build: .
    command: bash -c "pip3 install psycopg2 && python manage.py makemigrations && python manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./vote_tech:/code
    ports:
      - "8000:8000"